// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class TestingTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }

    @Test
    public void testing() {
        driver.get("https://www.softwaretestingmaterial.com/");
        driver.manage().window().setSize(new Dimension(1363, 645));
        driver.findElement(By.id("onesignal-slidedown-cancel-button")).click();
        js.executeScript("window.scrollTo(0,262)");
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.cssSelector(".wp-image-19482")).click();
        vars.put("win965", waitForWindow(2000));
        driver.switchTo().window(vars.get("win965").toString());
        driver.findElement(By.id("closeIconHit")).click();
        driver.switchTo().frame(10);
        {
            WebElement element = driver.findElement(By.cssSelector(".smb-300x250-item:nth-child(1) img"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.switchTo().defaultContent();
        js.executeScript("window.scrollTo(0,17)");
        js.executeScript("window.scrollTo(0,156)");
    }
}
